name: IP Release ZIP for Dict

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab
  push:
    tags:
      - '*'  # Run on any tag

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Dict folder
        run: |
          zip -r Dict.zip Dict

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Dict.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
